ARG NODE_TAG=12
ARG NGINX_TAG=alpine
ARG APP_HOME=/home/node/app

# build stage
FROM node:${NODE_TAG} as build
ARG NODE_TAG
ARG APP_HOME
ARG API_HOST

WORKDIR ${APP_HOME}
COPY package*.json ${APP_HOME}/
RUN npm install

COPY . .
ENV REACT_APP_API_HOST=${API_HOST}
RUN REACT_APP_API_HOST=$REACT_APP_API_HOST npm run build 

# deploy stage
FROM nginx:${NGINX_TAG}
ARG NGINX_TAG
ARG APP_HOME
COPY --from=build ${APP_HOME}/build /usr/share/nginx/html

# WORKDIR /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
